name: 'Build, Test & Analysis'

on: [push]

jobs:
  pull_request_build_analysis:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build, unit tests and slice tests with Maven
        run: mvn -B clean package -f pom.xml -Dtest='com.urjc.mca.tfm.generateuml.model.**'

      - name: Save Jacoco Exec
        uses: actions/upload-artifact@v2
        with:
          name: jacoco_coverage.exec
          path: target/jacoco.exec

      - name: Save Jacoco XML Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco_coverage_report.xml
          path: target/site/jacoco/jacoco.xml

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B sonar:sonar \
          org.jacoco:jacoco-maven-plugin:prepare-agent verify \
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey='pjcalvo84_UMLDiagramsLib' \
          -Dsonar.projectName='UMLDiagramsLib' \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=pjcalvo84 \
          -Dsonar.branch=master \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.java.coveragePlugin=jacoco \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
