name: 'Build, Test & Analysis'

on: [push]

jobs:
  pull_request_build_analysis:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build, unit tests and slice tests with Maven
        run: mvn -B clean package -f pom.xml -Dtest='com.urjc.mca.tfm.generateuml.model.**'

      - name: Save Jacoco Exec
        uses: actions/upload-artifact@v2
        with:
          name: jacoco_coverage.exec
          path: target/jacoco.exec

      - name: Save Jacoco XML Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco_coverage_report.xml
          path: target/site/jacoco/jacoco.xml

  sonarcloud:
      - runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
